import type { Metadata } from "next";
import { Bruno_Ace } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const brunoAce = Bruno_Ace({
  variable: "--font-audiowide",
  weight: "400",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${brunoAce.className} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
